// <auto-generated />
using System;
using Backend.Persistence.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Srbopoly_backend.Migrations
{
    [DbContext(typeof(SrbopolyContext))]
    partial class SrbopolyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Persistence.Entities.BoardEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.GameEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CurrentPlayerIndex")
                        .HasColumnType("int");

                    b.Property<int>("CurrentTurn")
                        .HasColumnType("int");

                    b.Property<int>("MaxTurns")
                        .HasColumnType("int");

                    b.Property<string>("RewardCardsDeckIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SurpriseCardsDeckIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.PlayerEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsInJail")
                        .HasColumnType("bit");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.PropertyFieldEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BoardId")
                        .HasColumnType("int");

                    b.Property<int>("GameFieldID")
                        .HasColumnType("int");

                    b.Property<int>("Hotels")
                        .HasColumnType("int");

                    b.Property<int>("Houses")
                        .HasColumnType("int");

                    b.Property<int?>("OwnerID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BoardId");

                    b.HasIndex("OwnerID");

                    b.ToTable("PropertyFields");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.BoardEntity", b =>
                {
                    b.HasOne("Backend.Persistence.Entities.GameEntity", "Game")
                        .WithOne("Board")
                        .HasForeignKey("Backend.Persistence.Entities.BoardEntity", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.PlayerEntity", b =>
                {
                    b.HasOne("Backend.Persistence.Entities.GameEntity", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Persistence.Entities.UserEntity", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.PropertyFieldEntity", b =>
                {
                    b.HasOne("Backend.Persistence.Entities.BoardEntity", "Board")
                        .WithMany("PropertyFields")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Persistence.Entities.PlayerEntity", "Owner")
                        .WithMany("OwnedFields")
                        .HasForeignKey("OwnerID");

                    b.Navigation("Board");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.BoardEntity", b =>
                {
                    b.Navigation("PropertyFields");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.GameEntity", b =>
                {
                    b.Navigation("Board")
                        .IsRequired();

                    b.Navigation("Players");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.PlayerEntity", b =>
                {
                    b.Navigation("OwnedFields");
                });

            modelBuilder.Entity("Backend.Persistence.Entities.UserEntity", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
